### ISSUE TITLE
When the external display screen is connected, there is an extra part of the screen frame

### ISSUE THREAD

**Issue by imzqqq** [wangwenx190/framelesshelper#47] opened 2021-03-09 07:02 UTC
I connected an external monitor, and the problem as shown in the picture occurred, but when I re-sized, maximized, or minimized, it returned to normal.

![WeChat Screenshot_20210309145802](https://user-images.githubusercontent.com/38660211/110430923-0cc5f500-80e8-11eb-94e3-f0cac7780b45.png)

**Comment by wangwenx190** [comment] 2021-03-09 07:10
That's weired! After it returns normal, will it become what the picture shows again? Can you provide your OS version number and the DPI you set (of that external monitor)?

**Comment by imzqqq** [comment] 2021-03-09 10:28
Another problem I ran into when I copied your library was that the time label and the three buttons in the upper right corner had backgrounds, and I basically didn't change the code.

![WeChat Screenshot_20210309182337](https://user-images.githubusercontent.com/38660211/110456541-a7ccc800-8104-11eb-883e-cc9321e272dd.png)

**Comment by wangwenx190** [comment] 2021-03-09 12:01
>
> Another problem I ran into when I copied your library was that the time label and the three buttons in the upper right corner had backgrounds, and I basically didn't change the code.
>
That's a totally different bug, please open a new issue and we'll discuss it there.

**Comment by JulienMaille** [comment] 2021-03-12 11:06
@wangwenx190 I believe this is exactly the same bug as the old one triggered by moving the window from one screen to another.
You said you removed the fix because of performance concerns, but could you show me the commit so I can at least try on my side? Thanks

**Comment by wangwenx190** [comment] 2021-03-13 02:09
>
> could you show me the commit so I can at least try on my side?
>
@JulienMaille I've just come up with a new solution for it, with no performance issues, I'll upload it in a few hours.

**Comment by wangwenx190** [comment] 2021-03-13 03:09
@JulienMaille Could you try whether commit 0d7f3dba7e69ed48686b453fe566a2052b8d1e0a fixes the issue or not if you have time?

**Comment by JulienMaille** [comment] 2021-03-13 09:27
I tried remotely on my 2 screen pc, it works although I can see some short lag. But it could come from the remove session.

**Comment by wangwenx190** [comment] 2021-03-13 09:36
>
> I can see some short lag
>
I'm making the thread sleep for some time to let the OS do the actual resize action, I'm not sure whether the lag is caused by this or not.

>
> Maybe screenChanged could perform the first resize() and set a flag that is then read when users stops dragging the window. This way you could trigger the 2nd resize() when the window stopped being moved.
>
Easy to achieve, but I don't have a second monitor, it's really hard for me to test this kind of scenarios.

**Comment by JulienMaille** [comment] 2021-03-13 10:47
I'll give it a try on my 2 monitor system next week

**Comment by wangwenx190** [comment] 2021-03-16 01:16
Maybe I can close this issue now?

**Comment by wangwenx190** [comment] 2021-03-16 12:09
The two bugs mentioned in this issue are both fixed in latest commit.

**Closed by wangwenx190** 2021-03-16 12:09 UTC
