### ISSUE TITLE
Missing top frame + context menu

### ISSUE THREAD

**Issue by JulienMaille** [wangwenx190/framelesshelper#23] opened 2020-10-09 10:09 UTC
I've 2 questions regarding the toolbar. Is it a known issue that the top frame is not drawn?
It happens on both examples
![image](https://user-images.githubusercontent.com/182520/95570982-08f25180-0a28-11eb-9610-cb17447d27b4.png) ![image](https://user-images.githubusercontent.com/182520/95571002-10195f80-0a28-11eb-852c-7f68aba8dc9e.png)

Also I was wondering if there is a way to emulate the right click context menu we usually have with native Windows frames.
![image](https://user-images.githubusercontent.com/182520/95571137-3e973a80-0a28-11eb-8ce8-b93f44e7ecb8.png)

**Comment by wangwenx190** [comment] 2020-10-09 10:30
>
> the top frame is not drawn
>

Yes, if you want to get rid of the title bar provided by Windows, the top frame will get lost at the same time. There is one way I know to bring it back, but it doesn't work with `QAbstractNativeEventFilter`. I also spent a lot of time to find the solution, but currently no progress have been made, so sad.

You can draw a border line manually, by `QPainter` (for QWidgets) or `Rectangle` (for Qt Quick).

If you really want to use the system top frame, you can try [the win10-only branch](https://github.com/wangwenx190/framelesshelper/tree/win10-only).

>
> if there is a way to emulate the right click context menu
>

Here's how Firefox does it:

```cpp
static bool DisplaySystemMenu(HWND hWnd, nsSizeMode sizeMode, bool isRtl,
                              int32_t x, int32_t y) {
  HMENU hMenu = GetSystemMenu(hWnd, FALSE);
  if (hMenu) {
    MENUITEMINFO mii;
    mii.cbSize = sizeof(MENUITEMINFO);
    mii.fMask = MIIM_STATE;
    mii.fType = 0;

    // update the options
    mii.fState = MF_ENABLED;
    SetMenuItemInfo(hMenu, SC_RESTORE, FALSE, &mii);
    SetMenuItemInfo(hMenu, SC_SIZE, FALSE, &mii);
    SetMenuItemInfo(hMenu, SC_MOVE, FALSE, &mii);
    SetMenuItemInfo(hMenu, SC_MAXIMIZE, FALSE, &mii);
    SetMenuItemInfo(hMenu, SC_MINIMIZE, FALSE, &mii);

    mii.fState = MF_GRAYED;
    switch (sizeMode) {
      case nsSizeMode_Fullscreen:
        // intentional fall through
      case nsSizeMode_Maximized:
        SetMenuItemInfo(hMenu, SC_SIZE, FALSE, &mii);
        SetMenuItemInfo(hMenu, SC_MOVE, FALSE, &mii);
        SetMenuItemInfo(hMenu, SC_MAXIMIZE, FALSE, &mii);
        break;
      case nsSizeMode_Minimized:
        SetMenuItemInfo(hMenu, SC_MINIMIZE, FALSE, &mii);
        break;
      case nsSizeMode_Normal:
        SetMenuItemInfo(hMenu, SC_RESTORE, FALSE, &mii);
        break;
      case nsSizeMode_Invalid:
        NS_ASSERTION(false, "Did the argument come from invalid IPC?");
        break;
      default:
        MOZ_ASSERT_UNREACHABLE("Unhnalded nsSizeMode value detected");
        break;
    }
    LPARAM cmd = TrackPopupMenu(
        hMenu,
        (TPM_LEFTBUTTON | TPM_RIGHTBUTTON | TPM_RETURNCMD | TPM_TOPALIGN |
         (isRtl ? TPM_RIGHTALIGN : TPM_LEFTALIGN)),
        x, y, 0, hWnd, nullptr);
    if (cmd) {
      PostMessage(hWnd, WM_SYSCOMMAND, cmd, 0);
      return true;
    }
  }
  return false;
}
```

Sadlly I'm not familiar with these APIs so I can't tell you more about this.

**Comment by JulienMaille** [comment] 2020-10-09 11:58
> You can draw a border line manually, by `QPainter` (for QWidgets) or `Rectangle` (for Qt Quick).

May I ask how I can query for the currently set border (frame) color?

**Comment by wangwenx190** [comment] 2020-10-09 13:18
>
> how I can query for the currently set border (frame) color
>
1. `DwmGetColorizationColor`: <https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmgetcolorizationcolor>
2. Read `ColorizationColor` under `HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`
>
> how I can catch the right click event from `WinNativeEventFilter:nativeEventFilter()`
>
Sorry I don't know.

**Comment by wangwenx190** [comment] 2020-10-09 13:21
>
> how I can catch the right click event from `WinNativeEventFilter:nativeEventFilter()`
>
Maybe you can capture mouse events in QWidget/QMainWindow (it's much more easier) and then trigger your `displaySystemMenu()`. You can make it a static function so you'll be able to call it like this: `WinNativeEventFilter::displaySystemMenu()`.

**Comment by wangwenx190** [comment] 2020-10-09 13:29
>
> Is it a known issue that the top frame is not drawn?
>
You can remove `WNEF_WIN10_HAS_WINDOW_FRAME` from `DEFINES` in the .pro file and the whole window frame will be hidden (not only the top frame), that will make the frameless window look less broken. Did you try this before?

**Comment by wangwenx190** [comment] 2020-10-10 03:59
>
> You can make it a static function so you'll be able to call it like this: `WinNativeEventFilter::displaySystemMenu()`
>
I'll add it in later commits.

**Comment by wangwenx190** [comment] 2020-10-10 04:01
>
> You can remove `WNEF_WIN10_HAS_WINDOW_FRAME` from `DEFINES` in the .pro file
>
It has been removed by myself. You can try to replace the `#if 1` with `#if 0` instead:
https://github.com/wangwenx190/framelesshelper/blob/5087c473f6acf50d12da0c1bb1c57d23e604fd70/winnativeeventfilter.cpp#L186

**Comment by wangwenx190** [comment] 2020-10-10 09:20
Do you have time to test the newly introduced function `WinNativeEventFilter::displaySystemMenu()`?
https://github.com/wangwenx190/framelesshelper/blob/3ffc8fd6812117ee9caac0054b7f6f39c2d47fe7/winnativeeventfilter.h#L133

**Comment by JulienMaille** [comment] 2020-10-10 09:25
I tried on my side when you shared the firefox example. I can tell it does display the context menu as expected.
Now if would be nice if we could catch the right click from `WinNativeEventFilter` and call the context menu on the right `HWND` maybe the connection could be done in `updateQtFrame_internal`?

**Comment by wangwenx190** [comment] 2020-10-11 03:27
>
> maybe the connection could be done in `updateQtFrame_internal`?
>
According to <https://docs.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu>, it seems we should do this in the `WM_CONTEXTMENU` block. But it doesn't work:
https://github.com/wangwenx190/framelesshelper/blob/e14f027277e4d33aad69d37d6bef4a2187b5858c/winnativeeventfilter.cpp#L1850
The context menu never show up. Currently don't know why.

**Comment by JulienMaille** [comment] 2020-10-11 07:23
`case WM_CONTEXTMENU` does show up when you press the contextmenu button on your keyboard. That's how I tried `displaySystemMenu` initially

**Comment by wangwenx190** [comment] 2020-10-11 09:40
>
> press the contextmenu button on your keyboard
>
May I ask what key it is? If it's Alt + Space, the context menu will always show up, before I add the `displaySystemMenu` function.

But according to Microsoft's docs, the context menu should also show up when the user clicks the right button, but actually it has no effect at all.

**Comment by wangwenx190** [comment] 2020-10-11 09:43
>
> May I ask what key it is?
>
All right, it's Shift + F10

**Comment by wangwenx190** [comment] 2020-10-11 09:46
> 
> 
> > You can remove `WNEF_WIN10_HAS_WINDOW_FRAME` from `DEFINES` in the .pro file
> 
> It has been removed by myself. You can try to replace the `#if 1` with `#if 0` instead:
> 
> https://github.com/wangwenx190/framelesshelper/blob/5087c473f6acf50d12da0c1bb1c57d23e604fd70/winnativeeventfilter.cpp#L186

Did you try this? It will save you much time because you don't have to draw the border line yourself.

**Comment by JulienMaille** [comment] 2020-10-11 11:10
No I've not tried yet. My plan was to draw the border myself, monitor frame color changes and commit this to my qmainwindow example once it's clean

**Comment by JulienMaille** [comment] 2020-10-11 11:10
> > May I ask what key it is?
> 
> All right, it's Shift + F10

![image](https://user-images.githubusercontent.com/182520/95677041-24459400-0bc3-11eb-8fc5-7e5023c1accb.png)

**Comment by wangwenx190** [comment] 2020-10-11 11:48
>
> My plan was to draw the border myself, monitor frame color changes
>
You can have a look at [the win10-only branch](https://github.com/wangwenx190/framelesshelper/tree/win10-only):

https://github.com/wangwenx190/framelesshelper/blob/cdab0dff14cf1262a629a50f964f34589a0b8643/qwinwidget.cpp#L581

Hacking into the `WM_PAINT` message is the only way I know to bring back the top frame, but that solution doesn't work well for `QAbstractNativeEventFilter` because Qt engineer told me doing this will break the painting mechanism of Qt. There won't be any official support for it. And I don't know how to solve this either.

By the way, how do you monitor frame color changes? The `WM_DWMCOLORIZATIONCOLORCHANGED` message? I tried to do this before, but the message doesn't come in time so the frame color doesn't change in time. Maybe you have better solution?


>
> commit this to my qmainwindow example once it's clean
>
That sounds great. I'm looking forward to your code!


> 
> 
> > > May I ask what key it is?
> > 
> > 
> > All right, it's Shift + F10
> 
> ![image](https://user-images.githubusercontent.com/182520/95677041-24459400-0bc3-11eb-8fc5-7e5023c1accb.png)

Thanks for your picture. I remember this key. But I'm using a laptop so I don't have this key. Anyway, Shift + F10 can emulate (or simulate? not good at English, sorry) this key.

**Comment by wangwenx190** [comment] 2020-10-11 11:58
>
> draw the border myself
>
And you have to know it's only supported on Windows 10. My code will hide the whole window frame on Windows 7, 8 and 8.1, unconditionally.

Here is the reason:

First we assume the DPI is 96, which means no automatic scalling by Qt or the system. The border line on Win10 is 1px, however, it become 8px on Win7 to Win8.1. The window will look very strange if you still preserve the window frame on Win7 to Win8.1 (you can try it yourself using the win10-only branch, it can be run on Win7 as well). Actually, the border line is in the client area on Win10, but non-client area on older systems.

**Comment by JulienMaille** [comment] 2020-10-11 13:21
Thanks for point this out. Then I will probably hide the frame, maybe you should keep the #define then, what do you think?

**Comment by wangwenx190** [comment] 2020-10-11 14:21
I prefer hide the window frame totally even on Win10 because that gives you the most consistent appearance on all versions of Windows. And you don't have to draw the top frame manually and monitor the frame color in case it changes.

But honestly speaking, it's a real pain to loose the window frame on Win10. I think you can still continue your original plan to see if it works well. If your solution works, I can improve this repo as well. Just give it a try.

**Comment by wangwenx190** [comment] 2020-10-11 14:24
But don't worry, you can switch between the two solutions easily through the `#define`. This repo supports both solution, only lacks drawing the top frame and monitor the frame color.

**Comment by wangwenx190** [comment] 2020-10-11 14:26
As for the DPI problem mentioned in other issues, it's a bug indeed, but it's Qt's own bug, not this repo's, so I won't try to fix it.

**Comment by wangwenx190** [comment] 2020-10-11 14:28
Now I just want to figure out how to trigger the context menu from mouse.

**Comment by JulienMaille** [comment] 2020-10-11 15:18
It seems we should monitor `WM_NCRBUTTONDOWN`  see https://codersatellite.com/question-with-identifier-21691352
But I tried and it's never fired, maybe `setContextMenuPolicy` has to be changed on the widget?

**Comment by wangwenx190** [comment] 2020-10-12 01:11
> 
> 
> It seems we should monitor `WM_NCRBUTTONDOWN` see <https://codersatellite.com/question-with-identifier-21691352>
> But I tried and it's never fired, maybe `setContextMenuPolicy` has to be changed on the widget?
>
>
No matter it's `setContextMenuPolicy`'s problem or not, we only need to monitor `WM_CONTEXTMENU`. According to MS's docs, `WM_CONTEXTMENU` will be fired when:
1. Right click on the client area (`WM_RBUTTONUP`)
2. Right click on the non-client area (`WM_NCRBUTTONUP`)
3. Keyboard (Shift + F10 or the context menu key)

See: <https://docs.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu>

**Comment by JulienMaille** [comment] 2020-10-12 09:11
Don't your code hide the "non client area"? That would expect why we do not receive any mouse click

**Comment by JulienMaille** [comment] 2020-10-12 09:40
> > > You can remove `WNEF_WIN10_HAS_WINDOW_FRAME` from `DEFINES` in the .pro file
> > 
> > 
> > It has been removed by myself. You can try to replace the `#if 1` with `#if 0` instead:
> > https://github.com/wangwenx190/framelesshelper/blob/5087c473f6acf50d12da0c1bb1c57d23e604fd70/winnativeeventfilter.cpp#L186
> 
> Did you try this? It will save you much time because you don't have to draw the border line yourself.

If I do this, it seems that the top resize region is only 1pixel, very hard to grab.

**Comment by wangwenx190** [comment] 2020-10-12 11:12
> 
> 
> Don't your code hide the "non client area"? That would expect why we do not receive any mouse click
>
Actually, the non-client area is covered by the client area, that's what we do in the `WM_NCCALCSIZE` block. But according to MS's docs, the `WM_CONTEXTMENU` should also be fired when we click in the client area.

And I tested `WM_RBUTTONDOWN`, `WM_RBUTTONUP`, `WM_NCRBUTTONDOWN` and `WM_NCRBUTTONUP`, the context menu doesn't show up as before.

>
> If I do this, it seems that the top resize region is only 1pixel, very hard to grab.
>
I can't reproduce this with the QMainWindow example written by yourself.

**Comment by wangwenx190** [comment] 2020-10-12 11:19
> 
> 
> It seems we should monitor `WM_NCRBUTTONDOWN` see https://codersatellite.com/question-with-identifier-21691352
>
That web page said he/she used `WM_NCRBUTTONUP` to show the context menu. But you wrote `WM_NCRBUTTONDOWN`. Is this a typo or something?

**Comment by wangwenx190** [comment] 2020-10-12 11:24
>
> I can't reproduce this with the QMainWindow example written by yourself.
>

<https://github.com/wangwenx190/framelesshelper/tree/master/examples/QMainWindow>

The resize area is about 8px height (when DPI is 96).

**Comment by JulienMaille** [comment] 2020-10-12 16:10
> > It seems we should monitor `WM_NCRBUTTONDOWN` see https://codersatellite.com/question-with-identifier-21691352
> 
> That web page said he/she used `WM_NCRBUTTONUP` to show the context menu. But you wrote `WM_NCRBUTTONDOWN`. Is this a typo or something?

Yes it's a typo sorry

**Comment by wangwenx190** [comment] 2020-10-16 08:03
@JulienMaille You can now test the new demo: <https://github.com/wangwenx190/framelesshelper/tree/master/examples/Win32Demo>

**Comment by JulienMaille** [comment] 2020-10-16 09:04
Great! except:
Dragging is laggy when blur is enabled
Resizable toggle doesn work (it's always resizable)
maximize icons is blurry

**Comment by wangwenx190** [comment] 2020-10-16 09:18
Thanks for testing it!

>
> Dragging is laggy when blur is enabled
>
I know this issue and it's a Windows 10 bug, not fixable from my side. I tested this demo in Win7 and Win8.1 few hours ago and the blur effect works perfectly.

>
> Resizable toggle doesn work (it's always resizable)
>
Does it work if you get rid the window frame? It may not work if you are using the window frame provided by the system, I'll fix it later.

>
> maximize icons is blurry
>
Not sure about the reason but I think it's not related to the frameless part. Since it's only a simple demo, I'm going to ignore it.

**Comment by wangwenx190** [comment] 2020-10-16 09:23
If you want to use the acrylic effect in Win10 for Win32 windows, you can change the following line
https://github.com/wangwenx190/framelesshelper/blob/0debbb890fdbe070ab959da7fd3d058db1fe4d6f/winnativeeventfilter.cpp#L2367
to:
https://github.com/wangwenx190/framelesshelper/blob/0debbb890fdbe070ab959da7fd3d058db1fe4d6f/winnativeeventfilter.cpp#L2371

`ACCENT_ENABLE_BLURBEHIND` is something like DWM blur, it's not the acrylic effect, but they look pretty similar to each other. The acrylic bug won't be triggered in this mode.

**Comment by wangwenx190** [comment] 2020-10-16 09:26
Even if you enabled the blur effect, if you don't set a palette for the window, the blur effect won't be seen. So don't forget it.
https://github.com/wangwenx190/framelesshelper/blob/0debbb890fdbe070ab959da7fd3d058db1fe4d6f/examples/Win32Demo/widget.cpp#L102

**Comment by wangwenx190** [comment] 2020-10-16 12:06
>
> Resizable toggle doesn work (it's always resizable)
>
Fixed in latest commit. A helper function was introduced in that commit, but don't use it for frameless windows, it's designed for normal windows only.

**Comment by wangwenx190** [comment] 2020-10-17 05:17
> 
> 
> > Resizable toggle doesn work (it's always resizable)
> 
> Fixed in latest commit. A helper function was introduced in that commit, but don't use it for frameless windows, it's designed for normal windows only.

New commit uploaded just now. The Win32Demo project is now more robust.

**Comment by wangwenx190** [comment] 2020-10-17 05:22
Summary:
>
> Dragging is laggy when blur is enabled
>
It's a bug of Windows 10 itself, not fixable from my side. Unless you use `ACCENT_ENABLE_BLURBEHIND` to replace `ACCENT_ENABLE_ACRYLICBLURBEHIND`.

>
> Resizable toggle doesn work (it's always resizable)
>
Fixed. The context menu is updated to match the window state (if the window is not resizable, the context menu is a little different).

>
> maximize icons is blurry
>
Not important and it's ignored by me for now.

**Comment by wangwenx190** [comment] 2020-10-17 05:23
If you have time to test the latest Win32Demo project, please let me know if you have any feedback.

**Comment by wangwenx190** [comment] 2020-10-17 05:24
Anyway, thanks for your participation!

**Comment by JulienMaille** [comment] 2020-10-17 08:23
Resize toggle is fixed.
The "blur" is just transparency, nothing like acrylic blur.

When using the windows frame and disabling resizing
 - alt+space: shows a context popup with resizing enabled
 - right-click on top bar: shows a context popup with resizing disabled

**Comment by wangwenx190** [comment] 2020-10-17 08:34
Thanks for testing it!
>
> The "blur" is just transparency, nothing like acrylic blur.
>
I know the reason now. A gradient color needs to be set. Will fix this in later commit.

> 
> When using the windows frame and disabling resizing
> 
>     * alt+space: shows a context popup with resizing enabled
> 
>     * right-click on top bar: shows a context popup with resizing disabled
>
I found this issue as well. But currently I don't know how to control the context menu brought up from alt+space yet.

**Comment by JulienMaille** [comment] 2020-10-17 09:39
I think you need something like
                accentPolicy.AccentFlags = 2;
                accentPolicy.GradientColor = (0x80 << 24) | (0x000000 & 0xFFFFFF);
https://stackoverflow.com/questions/32724187/how-do-you-set-the-glass-blend-colour-on-windows-10/41433592#41433592

**Comment by JulienMaille** [comment] 2020-10-17 09:39
By the way, when using the "context menu" key on the keyboard. We enter WM_CONTEXT, but later you check mouse position and discard context menu because the mouse is not over the titlebar

**Comment by wangwenx190** [comment] 2020-10-17 09:42
> 
> 
> I think you need something like
> accentPolicy.AccentFlags = 2;
> accentPolicy.GradientColor = (0x80 << 24) | (0x000000 & 0xFFFFFF);
> https://stackoverflow.com/questions/32724187/how-do-you-set-the-glass-blend-colour-on-windows-10/41433592#41433592

Yes, you are right. I've fixed this already. Just not uploaded yet. I'm still testing it.


> 
> 
> By the way, when using the "context menu" key on the keyboard. We enter WM_CONTEXT, but later you check mouse position and discard context menu because the mouse is not over the titlebar

Yes. What's wrong with it?

**Comment by JulienMaille** [comment] 2020-10-17 09:43
When using context menu key, I want the context menu to show, whatever the mouse position

**Comment by wangwenx190** [comment] 2020-10-17 09:45
> 
> 
> When using context menu key, I want the context menu to show, whatever the mouse position

It will show. I use `break` in that case, which means let Qt handle the event.

**Comment by wangwenx190** [comment] 2020-10-17 10:18
@JulienMaille New commit uploaded. The Acrylic effect now works as expected. I tested it on Win7, Win8.1 and Win10, the blur effect works perfectly (despite of the laggy dragging on Win10).

**Comment by wangwenx190** [comment] 2020-10-17 10:23
You can use a custom gradient color for the Acrylic effect:
https://github.com/wangwenx190/framelesshelper/blob/226bc52ece48f6057e22c726442decc09af3539b/winnativeeventfilter.h#L147
For this code, it's semi-transparent white by default.

**Comment by wangwenx190** [comment] 2020-10-17 10:40
> 
> 
> Even if you enabled the blur effect, if you don't set a palette for the window, the blur effect won't be seen. So don't forget it.
> 
> https://github.com/wangwenx190/framelesshelper/blob/0debbb890fdbe070ab959da7fd3d058db1fe4d6f/examples/Win32Demo/widget.cpp#L102

It's now done internally, no need to do it yourself.

> 
> 
> > Resizable toggle doesn work (it's always resizable)
> 
> Fixed in latest commit. A helper function was introduced in that commit, but don't use it for frameless windows, it's designed for normal windows only.

The function's internal logic has been changed. You can use it for both normal windows and frameless windows.



This repo is under active developing these days so APIs change very often, sorry for the inconvenience.

**Comment by JulienMaille** [comment] 2020-10-17 10:52
Any chance you could temporary switch to classic blur when moving window on win10?

**Comment by wangwenx190** [comment] 2020-10-17 11:14
> 
> 
> Any chance you could temporary switch to classic blur when moving window on win10?

Sure. Will add it in next commit. But before it, is the Acrylic effect looks normal now?

**Comment by wangwenx190** [comment] 2020-10-17 12:25
New commit uploaded. The blur effect on Windows 10 is changed back to the classic blur instead of the broken Acrylic effect. But you have to know it's still different from DWM blur. See the Win32Demo project about how to force enabling the Acrylic effect on Win10.

**Comment by wangwenx190** [comment] 2020-10-17 13:54
> Any chance you could temporary switch to classic blur when moving window on win10?

Maybe I misunderstood your question. I think the experience won’t be good to do so. The appearance of classic blur and the Acrylic effect is not exactly the same, if you keep switching between them, the window will look quite strange.

The updated Win32Demo project can switch between the classic blur and the Acrylic effect, you can try it and you’ll know what I mean.

**Comment by wangwenx190** [comment] 2020-10-18 03:54
The context menu issue is now solved! Checkout the latest code and test the Win32Demo project.

**Comment by wangwenx190** [comment] 2020-10-18 04:01
I'm closing this issue because we now have a workaround for the context menu problem. As for the top frame, we are discussing it in another issue already.

**Closed by wangwenx190** 2020-10-18 04:01 UTC
Labels: enhancement, help wanted

**Comment by wangwenx190** [comment] 2020-10-18 06:40
Tested on Fedora 32 just now and it works as expected. Some people say this repo has some issues on macOS, but I don't have a mac so I'm not able to test this repo on macOS.

**Comment by wangwenx190** [comment] 2020-10-19 07:15
The Win32Demo project has been updated just now. It now has four themed window borders on Win10. Can you test it?

**Comment by wangwenx190** [comment] 2020-10-19 07:25
The window may start flickering again when resizing.

The previous solution is to make the client area a little smaller than it should be, the flickering problem doesn't happen anymore indeed, however, it also means the "canvas" we use is smaller than what it should be. After some testing, I found it's causing many issues when I was trying to draw something manually by QPainter (Qt Quick is affected as well). So I commented out the line that reduce the client area. Now the flickering problem comes back but for now I don't know how to solve it without affecting the painting area of Qt yet.

**Comment by JulienMaille** [comment] 2020-10-19 09:01
There are small bugs when using blur and custom title bar

Blur is overflowing on the sides
![image](https://user-images.githubusercontent.com/182520/96423425-9b99aa00-11f9-11eb-9476-03f005599f17.png)

Left frame is visible on launch
![image](https://user-images.githubusercontent.com/182520/96423901-47db9080-11fa-11eb-9baf-dbcb921f3219.png)


Color selection doesn't change anything

**Comment by wangwenx190** [comment] 2020-10-19 09:07
>
> Blur is overflowing on the sides
>
It's not a bug. It's Microsoft's trick to make the resize area outside of a window. The overflowed area is the resize area, it's totally invisible unless you enable the blur effect.

>
> Left frame is visible on launch
>
The window is not updated in time. You can drag the left edge or right edge to make Qt update the window immediately.

**Comment by wangwenx190** [comment] 2020-10-19 09:11
>
> Color selection doesn't change anything
>
It selects the gradient color used by the Acrylic effect.

**Comment by JulienMaille** [comment] 2020-10-19 10:38
> > Color selection doesn't change anything
> 
> It selects the gradient color used by the Acrylic effect.

Ok but the blur effect is still the same grey

**Comment by wangwenx190** [comment] 2020-10-19 13:20
> 
> Left frame is visible on launch
> ![image](https://user-images.githubusercontent.com/182520/96423901-47db9080-11fa-11eb-9baf-dbcb921f3219.png)
> 
I can reproduce this issue now. It only happens when your DPI scale level is 100%. It will not happen when your DPI scale level is larger than 100%.

I've fixed it and will upload new code later.

**Comment by wangwenx190** [comment] 2020-10-19 13:43
> 
> 
> > > Color selection doesn't change anything
> > 
> > 
> > It selects the gradient color used by the Acrylic effect.
> 
> Ok but the blur effect is still the same grey

## You need to set the alpha channel to a non-zero value.

![图片](https://user-images.githubusercontent.com/17877450/96458670-c31d6080-1253-11eb-8211-02307486ab9a.png)


![图片](https://user-images.githubusercontent.com/17877450/96458540-9ff2b100-1253-11eb-99eb-9727ebd8cfc7.png)

**Comment by wangwenx190** [comment] 2020-10-20 02:09
You can test the latest Win32Demo project now. Despite of the resize area is still inside of the window, its appearance and behavior should be exactly the same with standard windows now.

**Comment by JulienMaille** [comment] 2020-10-20 18:47
It's quite nice now. The acrylic brush seems to have RGB channels reversed, don't you think so?

**Comment by wangwenx190** [comment] 2020-10-21 03:17
>
> The acrylic brush seems to have RGB channels reversed
>
Fixed by 8c21be9e64c445bd57f6e03e69da371b4025878e . It now works correctly.

**NOTE**

Set the alpha channel to 0: the brush color will always be some kind of semi-transparent gray.
Set the alpha channel to 255: the brush color will be totally opaque (except the white color).

You can set the alpha channel to 127 to get the most consistent behavior among all colors.

**Comment by wangwenx190** [comment] 2020-10-21 13:46
New commit uploaded. The Win32Demo project should look and behave exactly the same with a standard window now. The resize area is outside of the window and the top frame is not missing. What's more, the flickering problem when resizing is solved without affecting Qt's paint area.

Do you have time to test it?

**Comment by JulienMaille** [comment] 2020-10-21 14:41
on first start it show white text on white background
apart from that it is good

**Comment by wangwenx190** [comment] 2020-10-22 04:58
>
> on first start it show white text on white background
>
The initial acrylic brush color was changed to semi-transparent black, it should look better now. Actually, I could calculate the text color based on the background color but I think for a demo program the current solution is enough. Maybe I'll add this kind of function later.

**Comment by wangwenx190** [comment] 2020-10-22 12:02
>
> margin above buttons is gibber than native windows
>
The latest code may fixed this issue.

**Comment by wangwenx190** [comment] 2020-10-27 04:48
@JulienMaille Currently I'm working on making win32 windows frameless in QPA: <https://codereview.qt-project.org/c/qt/qtbase/+/318852>, in this way we can get rid of the title bar and preserve the top frame. Still working in progress, though. We can discuss more details there.

**Comment by JulienMaille** [comment] 2020-10-27 08:05
Great idea. I don't see any feedback so far. How can we help?

**Comment by wangwenx190** [comment] 2020-10-27 08:11
>
> I don't see any feedback so far
>
Because I haven't told anybody about this so far, except you.

>
> How can we help?
>
I need some testers to test this code when it's stable enough. I'll tell you about it when it's ready.

**Comment by wangwenx190** [comment] 2020-11-09 11:50
@JulienMaille The decision has been made to move all the code to the QtWinExtras module because it will make the QPA code too complicated.

**Comment by JulienMaille** [comment] 2020-11-09 12:14
Makes sense to move it to QtWinExtras, however dropping Win7 support is a bit of shame, considering the work you've already done, and the fact that many users are still using win7

**Comment by wangwenx190** [comment] 2020-11-09 12:29
> 
> 
> Makes sense to move it to QtWinExtras, however dropping Win7 support is a bit of shame, considering the work you've already done, and the fact that many users are still using win7

I don't want to drop it either, but Qt5 don't accept such big new change now. All new features must go in Qt6. And Qt6 will drop Win7 support, so it's meaningless to support Win7 in my code. It's a shame but I can't change this fact.

**Comment by JulienMaille** [comment] 2020-11-09 12:41
Oh you mean they won't backport it to Qt5?
With all the fuss surrounding Digia recent moves, and the fact many developer anticipate that Qt6 will be buggy for at least a couple releases, well, I'm not sure it's going to help your contribution to gain traction.
I don't want to sound harsh, but I believe it's better to keep it here.
Have you thought about opening a thread on their forum, in the showcase section if it still exists? Would be nice to have more developers using it!

**Comment by wangwenx190** [comment] 2020-11-09 13:29
>
> Oh you mean they won't backport it to Qt5?
>
Yes, there won't be any new features for the Qt5 series. All new features must target the 6.x releases. And Qt6 may only support 64 bit Windows 10 (1809 or newer) according to QTBUG-85851 and QTBUG-85855.

>
> I don't want to sound harsh, but I believe it's better to keep it here.
>
Don't worry, I'll keep maintaining this repo.

>
> Have you thought about opening a thread on their forum, in the showcase section if it still exists? Would be nice to have more developers using it! https://forum.qt.io/category/8/showcase
>
Thanks, I'll think about this.

**Comment by wangwenx190** [comment] 2020-11-09 13:31
I won't drop Win7 support in this repo. What I mean is to drop Win7 support in the new feature of Qt6.

**Comment by wangwenx190** [comment] 2020-11-10 04:38
The new work in QtWinExtras: <https://codereview.qt-project.org/c/qt/qtwinextras/+/321070>
